// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPo-fVm1jhiZwqJ7YwfzqafLLB1GQZZrk',
    appId: '1:69597270634:web:ac368568cec5e541667013',
    messagingSenderId: '69597270634',
    projectId: 'plants-app-flutter',
    authDomain: 'plants-app-flutter.firebaseapp.com',
    storageBucket: 'plants-app-flutter.appspot.com',
    measurementId: 'G-8QVYE20Y1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgWZi5fa2BnZQPsqHAuCRMKWwVIbj1LnE',
    appId: '1:69597270634:android:2662a61f3ee065ff667013',
    messagingSenderId: '69597270634',
    projectId: 'plants-app-flutter',
    storageBucket: 'plants-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBinIQVVdebNrfCDLSlIoEntTVT1CwQSWM',
    appId: '1:69597270634:ios:481485303241990f667013',
    messagingSenderId: '69597270634',
    projectId: 'plants-app-flutter',
    storageBucket: 'plants-app-flutter.appspot.com',
    iosBundleId: 'com.example.plantSelingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBinIQVVdebNrfCDLSlIoEntTVT1CwQSWM',
    appId: '1:69597270634:ios:2f6ec48b513234ad667013',
    messagingSenderId: '69597270634',
    projectId: 'plants-app-flutter',
    storageBucket: 'plants-app-flutter.appspot.com',
    iosBundleId: 'com.example.plantSelingApp.RunnerTests',
  );
}
